// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"database/sql"
)

type Category struct {
	ID          int64
	Name        string
	Description string
	Shortcode   string
	Createdat   int64
	Updatedat   sql.NullInt64
}

type Entry struct {
	ID         string
	Name       string
	Score      sql.NullInt64
	Userid     string
	Eventid    string
	Categoryid int64
	Createdat  int64
	Shortcode  string
	Updatedat  sql.NullInt64
}

type Event struct {
	ID            string
	Name          string
	Description   string
	Locationid    int64
	Visible       int64
	Eventdatetime int64
	Shortcode     string
	Createdat     int64
	Updatedat     sql.NullInt64
}

type EventCategory struct {
	Eventid    string
	Categoryid int64
}

type Location struct {
	ID        int64
	Name      sql.NullString
	Street    string
	Suburb    string
	State     string
	Postcode  string
	Createdat int64
	Updatedat sql.NullInt64
}

type Role struct {
	ID   int64
	Name string
}

type Session struct {
	ID     string
	Userid string
	Expiry int64
}

type User struct {
	ID        string
	Firstname string
	Lastname  string
	Email     string
	Role      int64
	Password  []byte
	Createdat int64
	Updatedat sql.NullInt64
}
