// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: register.sql

package sqlc

import (
	"context"
)

const checkEmailExistence = `-- name: CheckEmailExistence :one
SELECT
	1
FROM
	users
WHERE
	email = ?
`

func (q *Queries) CheckEmailExistence(ctx context.Context, email string) (int64, error) {
	row := q.db.QueryRowContext(ctx, checkEmailExistence, email)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO
	users (id, firstName, lastName, email, password)
VALUES
	(?, ?, ?, ?, ?)
`

type CreateUserParams struct {
	ID        string
	Firstname string
	Lastname  string
	Email     string
	Password  []byte
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Firstname,
		arg.Lastname,
		arg.Email,
		arg.Password,
	)
	return err
}
